{% set name = "yacron" %}
{% set version = "0.9.0" %}
{% set sha256 = "f54e02a1a37a06a8f972258095547c75f6e34404365b9985639a54a59acf133b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip
    - pytest-runner
    - setuptools_scm
  run:
    - python >=3.5
    - strictyaml >=0.7.2
    - crontab
    - aiohttp
    - raven
    - raven-aiohttp
    - aiosmtplib
    - jinja2

test:
  imports:
    - yacron

about:
  home: https://github.com/gjcarneiro/yacron
  summary: 'A modern Cron replacement that is Docker-friendly'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcs07
