{% set name = "yacron" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e2b657699847a9daa913e6e70b1a5e4a6e6d7d615e0063223ca7afd0e59c3a3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - yacron = yacron.__main__:main

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
    - setuptools_scm
  run:
    - python >=3.5
    - strictyaml >=0.7.2
    - crontab
    - aiohttp
    - sentry-sdk
    - aiosmtplib
    - jinja2
    - pytz

test:
  imports:
    - yacron
  commands:
    - yacron --version

about:
  home: https://github.com/gjcarneiro/yacron
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern Cron replacement that is Docker-friendly
  dev_url: https://github.com/gjcarneiro/yacron

extra:
  recipe-maintainers:
    - mcs07
