travis:
  secure:
    BINSTAR_TOKEN: chwjRG+byZ1EeJ7p2F5+JthZ6YJAKBtNbwpWMSFWkpbmdRWeMWd44QZ2YhXG9sgsYH94/hY+KlO3W72O1wbVvfwylFwjJOxjrzWbEBangrTeuwaO9ZSjAiSw8jbIfyHCA2rOxB8sM36Pz/VhNklFfJJhv388rdA4T6wmlUdzcgZRmZNtx/piHUwwcZhf0lnNKlE8EswoQd6dU0o+BSdhXjHIdtfM2bL7Qu7zAhK5jLoC34bbY6eTSSvYl36NAl/hmik7YzR0bWQX18Hnc2e6Yw4Ymue+rclt6r/ISJqrpj9Ph+k9IBtL3yZOH4RYr+J2njmaZnCHxNM2QgcWEwge1js6kEFyERJW5djqOTZnuMvg8Euzvv0uPuccNLt0rJhnYmqKzQWtpXTCn6/imsKANj6quj9NWmdMkTO4FHsYOP/VlgIhB1hhvPjMYpKNKTGGvy+0WAS9ZXYDxXoPY3uP9bXrRFdui1CfyZXmZRLxq/u2Deu6Go04n3znnb0nIiir6d8i34AVxEAhNY7z432fQYlT/HzJmwVg/PX5MG7+UimK1chQ3+9XTUjZgjoh4iiToxchzki8Xsi8gvz4a2xh5ORnRoOolsg5HGNqO+YfkrsJf18t50A12NKQQ4U1lF5E88S/8ol9R3xlHWnpUiNeDjjvdMT21SXejjjx86uFiMY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
