travis:
  secure:
    BINSTAR_TOKEN: VidtRvetQ3GDWzTwZhZHjJTnU4HmVjyvCHyc3XDdI4gFWTT1J025Zx24QRtiNdzcEpq/H0im0hcGtV8xpzAvWTHoOenm2dDNZZs/RvRWsj7BSaKsMm/6j1FdVsLNKK48t1h85qoAKFT0uyscutNk7QSR+rW1N3Jd81jAEPbNITdcVb3g1UYCcek5xI/+I3D0vKEaX39ddbaEcCXXAcG25CllnU1pgkviX3n0gToYNA4iBydBhB+MH0Lp6Hv1rFUgzXuYfmpnNCgdV081BFCxY1YwdvTboUAOx7wN9gSJtzjSjyv6t/0v0MgLIHH6dor9/7aX//JZg+WoxhY0+TpyWp1eP9TLTBI+6qFHeUgh6Ck0hkf4MQwO1dN9atBzG3AekkorI76+0tGRRmuJ5P5fzLH1+gDqkhZHPym60+I/D+rmnm2a2J/jvrM+iGFsnNad3Z17caSiBt0+FxOheILW5/rBetk9PZ0RMXJfN1YHWCfL+Yvgq4G9+0rcNDG2ODcDBBR+GKjn0U3tu2uAaRmCnUvd+V1xCt7bQ7i3QP9lGJlWtEO7G/RVu8ig7dPZxdNmyJyuKkHHzsPYH4iIMYBq4x+RJhCSeiQx71OWw8rmk5OeH5G8h16CezgFueESsLqBL2EarQvew+7jWaz3/knYAZka0yQYJSv1MVscv1ycq7A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
